# RDS variable
variable "region" {}
variable "allocated_storage" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "name" {}
variable "username" {}
variable "service" {}
variable "vpc_id" {}
variable "db_user" {}
variable "public_subnet_ids" {}
variable "public_subnet_group_name" {}
variable "private_subnet_a_id" {}
variable "private_subnet_b_id" {}
variable "lambda_security_group_id" {}
