# Generated by Django 4.1.3 on 2022-11-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmdbMoviesRawData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('budget', models.BigIntegerField()),
                ('genres', models.JSONField()),
                ('homepage', models.TextField()),
                ('keywords', models.JSONField()),
                ('original_language', models.CharField(max_length=30)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('production_companies', models.JSONField()),
                ('production_countries', models.JSONField()),
                ('release_date', models.DateField()),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('spoken_languages', models.JSONField()),
                ('status', models.CharField(choices=[('Released', 'Released'), ('Rumored', 'Rumored'), ('Other', 'Other')], max_length=20)),
                ('tagline', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TmdbCreditsRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cast', models.JSONField()),
                ('crew', models.JSONField()),
                ('movie', models.ForeignKey(db_column='movieId', on_delete=django.db.models.deletion.PROTECT, to='movie.tmdbmoviesrawdata')),
            ],
        ),
    ]
